# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'SwiftFBAudience' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftFBAudience

  pod 'FBAudienceNetwork', '= 4.27.2'
  pod 'mopub-ios-sdk', '= 4.18.0'

  target 'SwiftFBAudienceTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
