# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'ObjCSampleApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for ObjCSampleApp

#  pod 'mopub-ios-sdk', '= 4.18.0'
#  pod 'FBAudienceNetwork', '4.27.2'

  target 'ObjCSampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ObjCSampleAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
